CREATE TABLE "app"."teams" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."teams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"name" varchar(60) NOT NULL,
	"short_name" varchar(10) NOT NULL,
	"is_seasonal" boolean NOT NULL,
	"has_waitlist_members" boolean NOT NULL,
	"has_waitlist_public" boolean NOT NULL,
	"only_team_members" boolean NOT NULL,
	"are_events_public" boolean NOT NULL,
	"gender_id" bigint,
	"age_group_id" bigint,
	"rank_group_id" bigint,
	"team_rank_in_group" integer,
	"is_rank_public" boolean,
	"color_id" bigint,
	"is_text_white" boolean,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);--> statement-breakpoint
ALTER TABLE "app"."teams" ADD CONSTRAINT "teams_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."teams" ADD CONSTRAINT "teams_gender_id_fkey" FOREIGN KEY ("gender_id") REFERENCES "app"."genders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."teams" ADD CONSTRAINT "teams_age_group_id_fkey" FOREIGN KEY ("age_group_id") REFERENCES "app"."club_age_groups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."teams" ADD CONSTRAINT "teams_color_id_fkey" FOREIGN KEY ("color_id") REFERENCES "app"."colors"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "teams_club_id_idx" ON "app"."teams" USING btree ("club_id");
