CREATE TABLE "app"."team_seasons" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."team_seasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"team_id" bigint NOT NULL,
	"season_id" bigint NOT NULL,
	"min_signup" integer,
	"max_signup" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "team_seasons_team_id_season_id_key" UNIQUE("team_id","season_id"),
	CONSTRAINT "team_seasons_signup_range_check" CHECK (("min_signup" IS NULL) OR ("max_signup" IS NULL) OR ("max_signup" >= "min_signup"))
);--> statement-breakpoint
ALTER TABLE "app"."team_seasons" ADD CONSTRAINT "team_seasons_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "app"."teams"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."team_seasons" ADD CONSTRAINT "team_seasons_season_id_fkey" FOREIGN KEY ("season_id") REFERENCES "app"."seasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "team_seasons_season_id_idx" ON "app"."team_seasons" USING btree ("season_id");
