CREATE TABLE "app"."schedules" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."schedules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"team_season_id" bigint NOT NULL,
	"start_time" time NOT NULL,
	"rrule" varchar(255) NOT NULL,
	"duration_minutes" integer NOT NULL,
	"start_date" date,
	"end_date" date,
	"location_id" bigint,
	"location_group_id" bigint,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "schedules_duration_minutes_check" CHECK ("duration_minutes" > 0),
	CONSTRAINT "schedules_date_range_check" CHECK (("start_date" IS NULL) OR ("end_date" IS NULL) OR ("end_date" >= "start_date")),
	CONSTRAINT "schedules_one_location_ref_check" CHECK (("location_id" IS NULL) OR ("location_group_id" IS NULL))
);--> statement-breakpoint
ALTER TABLE "app"."schedules" ADD CONSTRAINT "schedules_team_season_id_fkey" FOREIGN KEY ("team_season_id") REFERENCES "app"."team_seasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."schedules" ADD CONSTRAINT "schedules_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "app"."locations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."schedules" ADD CONSTRAINT "schedules_location_group_id_fkey" FOREIGN KEY ("location_group_id") REFERENCES "app"."location_groups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "schedules_team_season_id_idx" ON "app"."schedules" USING btree ("team_season_id");
